### ISSUE TITLE
build script is hate

### ISSUE THREAD

**Issue by haraldsteinlechner** [vrvis/Aardvark.Fake#7]
![](http://i0.kym-cdn.com/photos/images/facebook/000/000/578/1234931504682.jpg)

build script needs rework:
 * either fake needs to be updated (so that it uses f# 4.1)
 * or paket.core needs to be removed from build script and simualted via cmd
 * or build script dies as a whole

@luithefirst @WalchAndreas

**Comment by WalchAndreas** [comment]
@haraldsteinlechner removed paket.core from build script!

**Comment by haraldsteinlechner** [comment]
![](http://s2.quickmeme.com/img/14/140b5483695386641c948708752a0663ef0e2f500d6cdab6175c881d626a5a60.jpg)

PS.: command output would be nice. e.g. via https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/ProcessHelper.fs#L138

@aszabo314 @WalchAndreas @luithefirst

**Comment by luithefirst** [comment]
https://stackoverflow.com/questions/2332127/realtime-console-output-redirection-using-process

**Comment by WalchAndreas** [comment]
command output is now redirected to console @haraldsteinlechner @luithefirst
